version: '3.7'

services:

  postgres:
    image: postgres:12.3    
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    environment: 
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 67108864  # 64MB
    networks: 
      - internal
    secrets:
      - postgres-passwd
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == data-worker
      restart_policy:
        condition: on-failure 
      update_config:
        order: stop-first 
      resources:
        reservations:
          cpus: '0.1'  
          memory: 128m
        limits:
          cpus: '1.0'
          memory: 512m         
    
  pgadmin:
    image: dpage/pgadmin4:4.22 
    volumes:
      - pgadmin-data:/var/lib/pgadmin   
    environment: 
      PGADMIN_DEFAULT_EMAIL: pgadmin@docker.local
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks: 
      - internal      
      - public  
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == data-worker
      labels:
        traefik.enable: 'true'
        traefik.http.routers.pgadmin.entrypoints: web-secure
        traefik.http.routers.pgadmin.rule: Host(`${PGADMIN_HOST}`)  
        traefik.http.routers.pgadmin.tls: 'true'      
        traefik.http.routers.pgadmin.service: pgadmin        
        traefik.http.services.pgadmin.loadbalancer.server.port: '80'
      restart_policy:
        condition: on-failure 
      update_config:
        order: stop-first 
      resources:
        reservations:
          cpus: '0.1'   
          memory: 128m
        limits:
          cpus: '0.5'
          memory: 512m 

  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data
    networks:
      - internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == app-worker  
      restart_policy:
        condition: on-failure  
      update_config:
        order: stop-first        
      resources:
        reservations:
          cpus: '0.1'
          memory: 128m      
        limits:
          cpus: '0.5'
          memory: 256m


networks:
  internal:
    external: true
  public:
    external: true

secrets:
  postgres-passwd:
    file: postgres-passwd


volumes:
  postgres-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/postgres-data
  pgadmin-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/pgadmin-data 
  redis-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/redis-data 
  