version: '3.7'

services:

  superset:
    image: amancevice/superset:0.35.2
    hostname: superset
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    configs:
      - source: superset-config-py
        target: /etc/superset/superset_config.py
    secrets:
      - superset-postgres-passwd        
    networks: 
      - internal      
      - edge  
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == app-worker
      labels:
        traefik.http.routers.superset.rule: Host(`${SUPERSET_HOST}`) 
        traefik.http.routers.superset.entrypoints: http
        traefik.http.routers.superset.service: superset        
        traefik.enable: 'true'
        traefik.http.services.superset.loadbalancer.server.port: '8088'
      restart_policy:
        condition: on-failure 
      update_config:
        order: stop-first 
      resources:
        reservations:
          cpus: '0.1'   
          memory: 128m
        limits:
          cpus: '0.5'
          memory: 512m


networks:
  internal:
    external: true
  edge:
    external: true
  

configs:
  superset-config-py:
    file: superset_config.py


secrets:
  superset-postgres-passwd:
    file: superset-postgres-passwd 
